version: '3'

services:

  data:
    build:
      context: ./data
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  alert:
    build:
      context: ./alert
      dockerfile: Dockerfile
    ports:
      - "3002:3002"

  alert-trigger:
    build:
      context: ./alertTrigger
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
  
  organization:
    build:
      context: ./organization
      dockerfile: Dockerfile
    ports:
      - "3004:3004"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

volumes:
  data:
  pgadmin-data:
