import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import PrivateRoute from '@/utils/PrivateRoute'

const inter = Inter({ subsets: ['latin'] })
import { SideBar } from '@/components/sidebar/SideBar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <PrivateRoute>
      <div className="flex flex-row w-full h-full">
        <SideBar />
        <div className="w-full h-full p-4"> { children } </div>
      </div>
    </PrivateRoute>
  )
}
